export let normalBoard = [
  [
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
  ],
  [
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
  ],
  [
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
  ],
  [
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
  ],
  [
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
  ],
  [
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
  ],
];

export let hardBoard = [
  [
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
  ],
  [
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
  ],
  [
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
  ],
  [
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
  ],
  [
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
    { char: "", status: "" },
  ],
];
